name = "Emilien Vimont"
rol = "Data Science Consultant"
email = "emilien.vimont@gmail.com"
phone = "+33 7 77 78 40 21"
birthday = "May 29, 1999"
location = "Paris, France"
avatar = "./config/assets/avatars/avatar.png"
username = "emil2000dza" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d199666.5651251294!2d-121.58334177520186!3d38.56165006739519!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x809ac672b28397f9%3A0x921f6aaa74197fdb!2sSacramento%2C%20CA%2C%20USA!5e0!3m2!1sen!2sbd!4v1647608789441!5m2!1sen!2sbd" 
presentation = """
I have always enjoyed studying, implementing and framing technical solutions involving natural language processing or any data science related issue. 
"""
