[[doing]]
title = "Data Science"
icon = "./config/assets/icons/ai.svg"
text = "Modeling complex business processes using data science or more traditional statistic methods."

[[doing]]
title = "Machine Learning"
icon = "./config/assets/icons/code.svg"
text = "Implementing predictive models or simpler approaches to answzr concrete problems."

[[doing]]
title = "Backend Engineering"
icon = "./config/assets/icons/database.svg"
text = "Building backend of platforms to power approaches developed."

[[doing]]
title = "Data Analysis"
icon = "./config/assets/icons/monitoring.svg"
text = "Analyzing different volumes of data to provide meaningful insights from structured or unstructured data."
