[[project]]
title = "DialoGPT fine-tuned for french language"
category = "Deep Learning"
image = "./config/assets/projects/dialogpt.png"
url = "https://github.com/emil2000dza/DialoGPT-fine-tuned-for-french-language"

[[project]]
title = "Restricted Boltzmann Machine for image generation"
category = "Statistics"
image = "./config/assets/projects/rbm.png"
url = "https://github.com/emil2000dza/rbm-for-image-generation"

[[project]]
title = "Protein Family dataset study"
category = "Machine Learning"
image = "./config/assets/projects/protein.jpg"
url = "https://github.com/emil2000dza/pfam-database-study"

[[project]]
title = "VGG-16 fine-tuned for real time emotion detection"
category = "Computer Vision"
image = "./config/assets/projects/emotion.png"
url = "https://github.com/emil2000dza/emotion-detection"

[[project]]
title = "Study of handwritten signatures"
category = "Statistical learning"
image = "./config/assets/projects/signature.png"
url = "https://github.com/emil2000dza/projets-apprentissage-statistique"