############## Education config #################
#################################################
[[education]]
title = "Victor Grignard Highschool"
timeline = "2017 — 2019"
description = "Highly intensive classes in advance mathematics and physics preparing for the competitive entrance examinations to the French ‘Grandes Écoles’"

[[education]]
title = "Telecom SudParis"
timeline = "2019 — 2022"
description = "Classes included : Statistical Learning, Deep Learning, Computer Vision, NLP, Optimization, Reinforcement Learning, Perception for autonomous systems, System Networks, Decision-Making Processes."

############## Experience config ################
#################################################
[[experience]]
title = "Software Engineer Intern"
timeline = "Summer 2020"
description = "-	Implementation of a chatbot scenario using the object-oriented Rasa library on Python,
-	Integration of a call functionality for a chatbot using the company’s API.
"

[[experience]]
title = "Research Assistant in NLP (Large Language Models)"
timeline = "Summer 2021"
description = "-	Fine-Tuning of the DialoGPT (GPT-2) conversational agent for the french language,
-	Scrapping and parsing data to create a safe french utterances dataset,
-	Presentation to a seminar and deployment of the final model  using Docker and Hugging Face.
"

[[experience]]
title = "Data Scientist Assistant, Ubisoft, Saint-Mandé, France"
timeline = "04/2022 - 10/2022"
description = " Semi-automate the data drift detection of a profiling tool developed by former Research Scientists of the team to match the needs of the Market Strategy teams using unsupervised and semi-supervised methods ,
-	Profiling the video game market based on user behavior detected on Reddit involving in-depth study of word/sentence-embeddings,
-	Review of a prototype mapping of the video game world to unify the company's global market vision.
"

[[experience]]
title = "Data Scientist Consultant, Sia Partners, Paris, Francece"
timeline = "11/2022 - Now"
description = "- Machine Learning Engineer for a host assistant and a search engine for public sector,
- Machine Learning Engineer for a major french publishing house,
- Data Scientist for a CAC-40 utilities company,
- Involvement in the R&D team dedicated to NLP : collaboration, training or supervision of other consultants on projects related to research and development and the use of LLMs for use cases encountered on assignment."

############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = false
show_bar = false
show_value = false

[[skill]]
title = "Web design"
value = "80%"

[[skill]]
title = "Graphic design"
value = "70%"

[[skill]]
title = "Branding"
value = "90%"

[[skill]]
title = "WordPress"
value = "50%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = false
show_value = false

[[language]]
title = "English"
value = "60%"

[[language]]
title = "French"
value = "50%"

[[language]]
title = "German"
value = "50%"