############### Section config ##################
#################################################
title = "Tech Stack"
enabled = true # false

############### Technologies ####################
#################################################
# General technology I have worked with
# name = "./.../../icon_path"
[technologies]
python = "./config/assets/icons/python.svg"
SQL = "./config/assets/icons/postgre.svg"
git = "./config/assets/icons/git.svg"
docker = "./config/assets/icons/docker.svg"
elastic = "./config/assets/icons/elastic.svg"
aws = "./config/assets/icons/aws.svg"
gcp = "./config/assets/icons/gcp.svg"
dataiku = "./config/assets/icons/dataiku.svg"
linux = "./config/assets/icons/linux.svg"